AdminTemplate/Models/Entities/Product.cs
using AdminTemplate.Models.Entities.Abstracts;

namespace AdminTemplate.Models.Entities;

public class Product : BaseEntity<Guid>
{
    public string Name { get; set; }
    public decimal UnitPrice { get; set; } = 0;
    public int CategoryId { get; set; }

    public Category? Category { get; set; }
}

AdminTemplate/Components/CategoryReportViewComponent.cs
using AdminTemplate.BusinessLogic.Repository.Abstracts;
using AdminTemplate.Models.Entities;
using AdminTemplate.ViewModels.Dashboard;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AdminTemplate.Components
{
    public class CategoryReportViewComponent : ViewComponent
    {
        private readonly IRepository<Category, int> _categoryRepo;

        public CategoryReportViewComponent(IRepository<Category, int> categoryRepo)
        {
            _categoryRepo = categoryRepo;
        }

        public IViewComponentResult Invoke()
        {
            var data = _categoryRepo.Get()
                .Include(x => x.Products)
                .Select(x => new CategoryReportViewModel()
                {
                    Name = x.Name,
                    ProductCount = x.Products.Count
                }).ToList();

            return View(data);
        }
    }
}

AdminTemplate/Controllers/HomeController.cs
using AdminTemplate.BusinessLogic.Repository;
using AdminTemplate.BusinessLogic.Repository.Abstracts;
using AdminTemplate.Models.Entities;
using AdminTemplate.ViewModels.Dashboard;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AdminTemplate.Controllers;

public class HomeController : Controller
{
    //private readonly MyContext _context;
    private readonly IRepository<Product, Guid> _productRepo;

    // GET
    public HomeController(IRepository<Product, Guid> productRepo)
    {
        _productRepo = productRepo;
    }

    public IActionResult Index()
    {
        var productReportViewModel = (_productRepo as ProductRepo).GetProductReport();
        
        var model = new DashboardViewModels()
        {
            ProductReportViewModel = productReportViewModel
        };
        return View(model);
    }
    [HttpGet, Authorize]
    public IActionResult Category()
    {
        return View();
    }

    [HttpGet,Authorize]
    public IActionResult Product()
    {
        return View();
    }
}

AdminTemplate/Views/Home/Category.cshtml
@{
    ViewBag.Title = "Kategori Sayfası";
}
<div class="row">
    <div class="col-md-12" id="cardListCategory">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h3 class="card-title">Kategori Listesi </h3>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="switch">
                    <label class="form-check-label" for="switch">Kategori Ekle</label>
                </div>
            </div>
            <div class="card-body">
                <ul id="listCategory" class="list-group d-flex justify-content-between">
                    <li class="list-group-item">Kategori Adı - Açıklama</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="cardAddCategory" style="display: none">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Kategori Ekle</h3>
            </div>
            <div class="card-body">
                <form id="formCategory">
                    <div class="mb-3 row">
                        <label for="txtCategoryName" class="col-sm-2 col-form-label">Kategori Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtCategoryName">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtDescription" class="col-sm-2 col-form-label">Açıklama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtDescription">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <input type="submit" value="Kaydet" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="cardUpdateCategory" style="display: none">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Kategori Güncelle</h3>
            </div>
            <div class="card-body">
                <form id="formUpdateCategory">
                    <div class="mb-3 row">
                        <label for="txtUpdateCategoryName" class="col-sm-2 col-form-label">Kategori Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtUpdateCategoryName">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtUpdateDescription" class="col-sm-2 col-form-label">Açıklama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtUpdateDescription">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <input type="submit" value="Güncelle" class="btn btn-primary" />
                    </div>
                    <input type="hidden" id="txtUpdateCategoryId" />
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
<script>
    $(() => {
        GetCategories();
        $("#switch").on("change",
            () => {
                if ($("#switch").is(":checked")) {
                    $("#cardListCategory").attr("class", "col-md-6");

                    $("#formCategory").trigger("reset");
                    $("#cardAddCategory").slideDown(750);
                } else {
                    $("#cardAddCategory").slideUp(750,
                        () => {
                            $("#cardListCategory").attr("class", "col-md-12");
                        });
                }
            });
        $("#formCategory").submit(e => {
            e.preventDefault();
            var data = {
                "name": $("#txtCategoryName").val(),
                "description": $("#txtDescription").val()
            }
            // $.ajax({}).done(callbackfunc).fail(callbackfunc);
            //ajax post
            //console.log(data);
            $.ajax({
                url: "../../api/categoryapi/add",
                method: "POST",
                data: JSON.stringify(data),
                headers: {
                    "Content-Type": "application/json"
                }
            }).done(data => {
                //alert(data.message);
                toastr["success"]("Kategori Ekleme", data.message);
                $("#formCategory").trigger("reset");
                GetCategories();
                $("#txtCategoryName").focus();
            }).fail(response => {
                toastr["error"]("Kategori Ekleme", response.responseJSON.message);
            });

        });

        $("#formUpdateCategory").submit(e => {
            e.preventDefault();
            var data = {
                name: $("#txtUpdateCategoryName").val(),
                description: $("#txtUpdateDescription").val(),
                id: $("#txtUpdateCategoryId").val()
            };

            $.ajax({
                url: "../../api/categoryapi/update/" + data.id,
                method: "PUT",
                data: JSON.stringify(data),
                headers: {
                    "Content-Type": "application/json"
                }
            }).done(data => {
                toastr["success"]("Kategori Ekleme", data.message);
                GetCategories();
                $("#cardUpdateCategory").slideUp(750);
                $("#formUpdateCategory").trigger("reset");
                $("#cardListCategory").attr("class", "col-md-12");
            }).fail(error => {
                toastr["error"]("Kategori Ekleme", error.responseJSON.message);
            });
        });
    });
    const GetCategories = () => {
        var settings = {
            "url": "../../api/categoryapi/all",
            "method": "GET"
        };

        $.ajax(settings).done(function(response) {
            //console.log(response);
            addToList(response);
        });
    };
    const addToList = (categories) => {
        const ul = $("#listCategory");
        ul.empty();
        categories.forEach(category => {
            const li = $("<li>");
            li.addClass("list-group-item");
            li.html(`${category.name} - ${category.description}`);
            //ul.append(li);
            li.appendTo(ul);

            const div = $("<div>");
            div.css("float", "right");
            const btnUpdate = $(`<input type='button' value='Güncelle' class='btn btn-primary' data-id='${category.id}' />`);

            btnUpdate.on("click",
                () => {
                    const id = $(btnUpdate).attr("data-id");
                    //apiden kategori detayını çek
                    //api/categoryapi/detail/${id}
                    $.ajax({
                        url: `../../api/categoryapi/detail/${id}`,
                        method: "GET"
                    }).done((response) => {
                        console.log(response);
                        $("#txtUpdateCategoryName").val(response.name);
                        $("#txtUpdateDescription").val(response.description);
                        $("#txtUpdateCategoryId").val(response.id);
                        $("#cardUpdateCategory").slideDown(750);
                        $("#cardListCategory").attr("class", "col-md-6");

                    }).fail((error) => {
                        console.log(error.responseJSON.message);
                    });
                });

            const btnDelete = $(`<input type='button' value='Sil' class='btn btn-danger' data-id='${category.id}' />`);

            btnDelete.on("click",
                () => {
                    const id = $(btnDelete).attr("data-id");
                    Swal.fire({
                        icon: 'question',
                        title: `${category.name} isimli kategori silinsin mi?`,
                        showCancelButton: true,
                        confirmButtonText: 'Sil',
                        cancelButtonText: `İptal`,
                    }).then((result) => {
                        /* Read more about isConfirmed, isDenied below */
                        //console.log(result);
                        if (result.isConfirmed) {
                            //ajax silme işlemi yapılacak

                            $.ajax({
                                url: `../../api/categoryapi/delete/${id}`,
                                method: "DELETE"
                            }).done(data => {
                                console.log(data);
                                toastr["success"]("Silindi", data.message);                    
                                GetCategories();
                            }).fail(data => {
                                console.log(data);
                            });
                            //Swal.fire('Kopyalandı!', pickerDiv.innerHTML, 'success')
                        } else {
                            Swal.fire('İptal', 'Silme işlemi iptal edildi', 'info');
                        }
                    });
                });

            div.append(btnUpdate).append(btnDelete).appendTo(li);

        });
    }

    toastr.options = {
        "closeButton": false,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "1000",
        "timeOut": "5000",
        "extendedTimeOut": "1000",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
    }
</script>
}

AdminTemplate/Views/Home/Index.cshtml
@model AdminTemplate.ViewModels.Dashboard.DashboardViewModels

@{
	ViewBag.Title = "Homepage";
}

<h1>Dashboard</h1>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <partial name="Partials/Dashboard/_ProductReportPartialView" model="Model.ProductReportViewModel"/>
        </div>
        <div class="col-md-4">
            @await Component.InvokeAsync("CategoryReport")
        </div>
    </div>
</div>

AdminTemplate/Views/Home/Product.cshtml
@{
    ViewBag.Title = "Ürün Sayfası";
}
<div class="row">
    <div class="col-md-12" id="cardListProduct">
        <div class="card">
            <div class="card-header d-flex justify-content-between">
                <h3 class="card-title ">Ürün Listesi </h3>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="switch">
                    <label class="form-check-label" for="switch">Ürün Ekle</label>
                </div>
            </div>
            <div class="card-body">
                <ul id="listProduct" class="list-group d-flex justify-content-between">
                    <li class="list-group-item">Ürün Adı - Fiyatı - Kategorisi</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="cardAddProduct" style="display: none">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Ekle</h3>
            </div>
            <div class="card-body">
                <form id="formProduct">
                    <div class="mb-3 row">
                        <label for="cmbCategory" class="col-sm-2 col-form-label">Kategorisi</label>
                        <div class="col-sm-10">
                            <select id="cmbCategory" class="custom-select">
                                <option>Bir kategori seçiniz</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtProductName" class="col-sm-2 col-form-label">Ürün Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtProductName">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtUnitPrice" class="col-sm-2 col-form-label">Fiyatı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtUnitPrice">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <input type="submit" value="Kaydet" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6" id="cardUpdateProduct" style="display: none">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Güncelle</h3>
            </div>
            <div class="card-body">
                <form id="formUpdateProduct">
                    <div class="mb-3 row">
                        <label for="cmbCategory" class="col-sm-2 col-form-label">Kategorisi</label>
                        <div class="col-sm-10">
                            <select id="cmbUpdateCategory" class="custom-select">
                                <option>Bir kategori seçiniz</option>
                            </select>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtUpdateProductName" class="col-sm-2 col-form-label">Ürün Adı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtUpdateProductName">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label for="txtUpdateUnitPrice" class="col-sm-2 col-form-label">Fiyatı</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="txtUpdateUnitPrice">
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <input type="submit" value="Güncelle" class="btn btn-primary" />
                    </div>
                    <input type="hidden" id="txtUpdateProductId" />
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(() => {
            getProducts();
            $("#switch").on("change",
                () => {
                    console.log("değişti");
                    if ($("#switch").is(":checked")) {
                        getCategoryLookup();
                        $("#cardListProduct").attr("class", "col-md-6");
                        $("#formProduct").trigger("reset");
                        $("#cardAddProduct").slideDown(750);
                    } else {
                        $("#cardAddProduct").slideUp(750,
                            () => {
                                $("#cardListProduct").attr("class", "col-md-12");
                            });
                    }

                });
            $("#formProduct").on("submit",
                (e) => {
                    e.preventDefault();
                    var data = {
                        categoryId: $("#cmbCategory").val(),
                        name: $("#txtProductName").val(),
                        unitPrice: $("#txtUnitPrice").val()
                    };
                    $.ajax({
                        url: "../../api/productapi/add",
                        method: "POST",
                        data: JSON.stringify(data),
                        headers: {
                            "Content-Type": "application/json"
                        }
                    }).done(data => {
                        console.log(data);
                        toastr["success"]("Ürün Ekleme", data.message);
                        getProducts();
                        $("#formProduct").trigger("reset"); // formu temizle
                    }).fail(error => {
                        console.log(error);
                    });
                });

            $("#formUpdateProduct").on("submit",
                (e) => {
                    e.preventDefault();
                    var data = {
                        categoryId: $("#cmbUpdateCategory").val(),
                        name: $("#txtUpdateProductName").val(),
                        unitPrice: $("#txtUpdateUnitPrice").val(),
                        id: $("#txtUpdateProductId").val()
                    };
                    $.ajax({
                        url: "../../api/productapi/update/"+data.id,
                        method: "PUT",
                        data: JSON.stringify(data),
                        headers: {
                            "Content-Type": "application/json"
                        }
                    }).done(data => {
                        console.log(data);
                        toastr["success"]("Ürün Güncelleme", data.message);
                        getProducts();
                        $("#cardUpdateProduct").slideUp(750,
                            () => {
                                $("#cardListProduct").attr("class", "col-md-12");
                            });
                    }).fail(error => {
                        console.log(error);
                    });
                });
        });

        const getProducts = () => {
            $.ajax({
                url: "../../api/productapi/all",
                method: "GET"
            }).done(data => {
                console.log(data);
                addProductList(data);
            }).fail(error => {
                console.log(error);
            });
        }

        const getCategoryLookup = () => {
            $.ajax({
                url: "../../api/categoryapi/all",
                method: "GET"
            }).done(data => {
                console.log(data);
                addCategoryLookup(data);
            }).fail(error => {
                console.log(error);
            });
        };

        const addCategoryLookup = (categories) => {
            $("#cmbCategory").empty();
            $("#cmbUpdateCategory").empty();
            categories.forEach(category => {
                $("#cmbCategory").append(`<option value="${category.id}">${category.name}</option>`);
                $("#cmbUpdateCategory").append(`<option value="${category.id}">${category.name}</option>`);
            });
        };

        const addProductList = (products) => {
            $("#listProduct").empty();
            products.forEach(product => {
                const li = $(`<li class="list-group-item">${product.name} - ${product.unitPrice}₺ - ${product.category.name}</li>`);
                //const li = $(`<li class="list-group-item">${product.name} - ${product.unitPrice} - ${product.categoryName}</li>`);

                const div = $(`<div class="btn-group float-right"></div>`);
                const btnUpdate = $(`<input type='button' class="btn btn-primary" value='Güncelle'>`);

                const btnDelete = $(`<input type='button' class="btn btn-danger" value='Sil'>`);

                btnDelete.on("click",
                    () => {
                        //swal ile silme onayı alınır
                        $.ajax({
                                url: "../../api/productapi/delete/" + product.id,
                                method: "DELETE"
                            })
                            .done(data => {
                                console.log(data);
                                //toastr ile bilgi verilmeli
                                toastr["success"]("Ürün Silme", data.message);                              
                                getProducts();
                            })
                            .fail(error => {
                                console.log(error);
                                //toast ile hata verilmeli
                            });
                    });

                btnUpdate.on("click",
                    () => {
                        getCategoryLookup();
                        $("#cardListProduct").attr("class", "col-md-6");
                        $("#formUpdateProduct").trigger("reset");
                        $("#cardUpdateProduct").slideDown(750);
                        $.ajax({
                            url: "../../api/productapi/detail/" + product.id,
                            method: "GET"
                        }).done(data => {
                            console.log(data);
                            $("#txtUpdateProductId").val(data.id);
                            $("#txtUpdateUnitPrice").val(data.unitPrice);
                            $("#txtUpdateProductName").val(data.name);
                            $("#cmbUpdateCategory").val(data.categoryId);
                        }).fail(error => {
                            console.log(error);
                        });
                        });

                div.append(btnUpdate).append(btnDelete).appendTo(li);

                $("#listProduct").append(li);
            });
        };
    </script>
}